[client]
showErrorDetails = true

[logger]
level = "error"

[client.toolbarMode]
mode = "minimal"

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"
